version: '3.4'

services:
  benchmark:
    build:
      context: .
      dockerfile: fixture.Dockerfile
      target: fixture
    command: benchmark --path /app/CodeChallenge/Target/CodeChallenge.Target
  debug:
    build:
      context: .
      dockerfile: fixture.Dockerfile
      target: fixture
    command: debug --path /app/CodeChallenge/Target/CodeChallenge.Target