version: '3.4'

services:
  baseline:
    build:
      context: .
      dockerfile: fixture.Dockerfile
      target: fixture
    command: benchmark --path /app/CodeChallenge.Baseline/CodeChallenge.Baseline
  debug:
    build:
      context: .
      dockerfile: fixture.Dockerfile
      target: fixture
    command: debug --path /app/CodeChallenge.Baseline/CodeChallenge.Baseline